name: Apply Formatters

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  apply-formatters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install black isort

      - name: Apply formatters
        run: |
          isort . --profile black
          black . --line-length 100

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
