name: Scan with Flake8
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 . --max-line-length=100